version: "2"

services:
  main:
    build: .
    ports:
     - "8080:8080"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PORT: "8080"
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      # LETSENCRYPT_TEST: "true"
      API_BASE_URI: ${API_BASE_URI}
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
