version: "2"

services:
  main:
    build: .
    ports:
     - "8080:8080"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PORT: "8080"
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # LETSENCRYPT_TEST: "true"
      CONSUMER_KEY: ${CONSUMER_KEY}
      CONSUMER_SECRET: ${CONSUMER_SECRET}
      OAUTH_TOKEN: ${OAUTH_TOKEN}
      OAUTH_TOKEN_SECRET: ${OAUTH_TOKEN_SECRET}
    restart: unless-stopped
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
